gns3/modules/virtualbox/__init__.py, gns3/modules/virtualbox/pages/virtualbox_preferences_page.py, gns3/modules/virtualbox/settings.py, gns3/modules/virtualbox/ui/virtualbox_preferences_page.ui, gns3/modules/virtualbox/ui/virtualbox_preferences_page_ui.py
This code change allowed me to have VirtualBox VMs and a Cloud device with Internet in GNS3 network at the same time.
(Tested only on Ubuntu Linux)
I ran GNS3 as a root user (required to configure Cloud devices to use my real PC's network cards):
> sudo gns3server (in one terminal window)
> sudo gns3 (in another terminal window)
But with GNS3 running as root, I could not add my VirtualBox non-root VMs to GNS3, because they did not show up in GNS3 VMs list.
To solve this problem, I made the changes to GNS3 server and GNS3 GUI code adding the following new setting to GNS3:
Edit -> Preferences... -> VirtualBox -> General -> General settings -> "Run VirtualBox as another user (GNS3 running as Linux root)"
By default, this field is empty, and when it is empty GNS3 runs as usual, as if there …
=> Run VirtualBox as another user

gns3/main_window.py
I think we have situation where the JSON export fail and the result is an empty topology file. We need to found why the JSON failed but with that we should not have an empty file.
Fix #290
=> I think it's prevent empty topologies

README.rst, requirements.txt
I've updated the readme with some of my experiences in trying to get GNS3 to compile from source on Windows. The instructions aren't fully complete, as I installed PyCrypto from a binary that I stumbled upon, and even its author isn't sure how he compiled it "back in the day" (see [here](https://github.com/axper/python3-pycrypto-windows-installer/issues/1#issuecomment-98202541)).
I've also modified the requirements.txt to reflect the setup.py state.
=> Windows readme + requirements ">=" instead of "=="

gns3/qt.py
In many places in GNS3, paths are left the same as how Qt would return them, which for Windows means that paths use "/" instead of Windows' native "\". If there's ever any replacement to the native separator, it's an afterthought... And it just looks out of place on Windows.
With this PR, the original PyQt path is always translated to whatever the native one is.
@noplay I knew you'll be proven right about PyQt being broken, and this providing a patch... But I didn't expected it to be *today* :laughing: .
=> Windows folder separator fix

gns3/dialogs/node_configurator_dialog.py
This one has been a minor annoyance to me ever since I first saw GNS3... I quickly realized the device list is useful when multiple nodes are configured at the same time, but it's overkill for a single device, and ultimately makes configurations cumbersome for newcomers (who tend to configure devices one by one, until they figure the whole thing out...).
I was trying to completely remove it in that case, or at least disable a resize of the splitter when the size is 0, but that requires too much refactoring for too little benefit, so this PR does the next best thing - the device list is simply hidden by default when there's only one device selected. Users can still pull it up by dragging the splitter from the left, and the list is there by default if more than one device is selected.
=> Hide device list in config dialog when only one device is selected

gns3/dialogs/text_editor_dialog.py, gns3/items/note_item.py
The title says it all.
I mean "Why not?".
The only sort of issue is that transparent text, just as white text currently, is effectively invisible in the settings dialog... <del>Should the background perhaps also be modified to always be the inverse color? The only color that would possibly be invisible that way would be rgb(127, 127, 127).</del> On second thought, one can always highlight the text if they're unsure, and anyway, it's better if one first writes the text, and only then modifies the color.
=> Allow alpha channel for text color

gns3/graphics_view.py
Zooming with the mouse wheel is broken with Qt5, due to Qt API changes.
This fix intentionally includes a check for the new method before applying it, falling back to the old, in order to make the zoom work in both Qt4 and Qt5.
Once GNS3 migrates fully to Qt5 (read: when the "import" patches become unnecessary), the check can be easily removed. In the meantime, this change should be pack portable to "master" too (though I've tested only with Qt5...).
=> CTRL+Wheel fix

gns3/modules/qemu/dialogs/qemu_image_wizzard.py, gns3/modules/qemu/ui/qemu_image_wizard.ui, gns3/modules/qemu/ui/qemu_image_wizard_ui.py
Is likely to fix #395.
(Untested on Linux, but works fine on Windows, and since there's no use of text() anywhere except the file location, it *should* work fine on Linux too)
=> Made Qemu image wizard text agnostic

gns3/iouvm-converter.py, gns3/iouvm_converter.py, gns3/main_window.py, gns3/ui/iouvm_converter_wizard.ui, gns3/ui/iouvm_converter_wizard_ui.py, gns3/ui/main_window.ui, gns3/ui/main_window_ui.py, setup.py
Add a wizard for converting an IOUVM to a GNS3VM:
* check in iourc if the gns3vm is present
* remove all remote servers from configuration (a warning explain to users they should not use the converter if they use their own remote servers)
* patch all IOU devices in config to use the GNS3 VM
* update the topologies in a specified directory in order to use GNS3VM in place of their remote server
All the files are backuped up before modification, an entry in the tools menu of GNS3 is added. We need to modify the build in order to create the binaries.
The command could be start with python `gns3/iouvm_converter.py`
Fix #531
=> IOUVM converter

gns3/dialogs/vm_wizard.py, gns3/modules/dynamips/dialogs/ios_router_wizard.py, gns3/modules/iou/dialogs/iou_device_wizard.py, gns3/modules/qemu/dialogs/qemu_vm_wizard.py, gns3/modules/virtualbox/dialogs/virtualbox_vm_wizard.py, gns3/modules/vmware/dialogs/vmware_vm_wizard.py, gns3/servers.py, tests/conftest.py, tests/test_servers.py
It's easier for using instead of searching the screen with use
local server options.
But I think it's not complete because we still have the checkbox
in the preferences.
When I read the code I found this:
https://github.com/GNS3/gns3-gui/blob/cd9bb16f79e8738fff34ff695730163b92c11170/gns3/modules/builtin/__init__.py#L72
And I'm not sure in which case it's call. I think it's only for
VPCS and things like Dynamips switch. Is it right? If it's the case
we can drop the checkbox from IOU, Qemu, VMware, VirtualBox
Also another question. Is actually if we show the VM choice by default if the VM is running. I'm not sure if it's a good idea for Dynamips. Do we want users to move all to the VM ? It's an open question.
=> Show the server choice in wizard if you have a VM or a remote server

gns3/pages/server_preferences_page.py, gns3/ui/server_preferences_page.ui, gns3/ui/server_preferences_page_ui.py
This PR allow user to have VNC port in the
console port range. It's not a problem because server
can share the range (we have a common list for all tcp ports).
And we add an informations in the settings in order to allow user
to know that 5900 => 6000 will be used.
Fix #846, #839
=> Allow to use the VNC port range for console

gns3/schemas/topology.json
I was making a topology with a device having a vmxnet3 interface, when a validation error popped up.
After tracking it down in the schema, I noticed it also misses several other network adapter types. This PR adds all of them, or at least all that are visible in the GNS3 1.4.0 GUI (I don't know if Qemu itself supports any additional ones), plus it intentionally formats them on multiple lines, ordered like the GUI list, for easier comparison, diff and additions in the future.
=> Added missing Qemu adapters to the topology schema.

gns3/registry/config.py
This PR adds the ability of .gns3a files to optionally specify desired disk interfaces for each HDD drive.
If present, they must be part of the qmu section, e.g.
````json
"qemu": {
"arch": "x86_64",
"adapter_type": "vmxnet3",
"hda_disk_interface": "virtio",
"boot_priority": "c",
"ram": 64,
"options": "-nographic",
"console_type": "telnet",
"adapters": 2
}
```
Defaults to "ide" when not present, which is what's ultimately used currently anyway.
=> Disk interfaces on Qemu appliances

gns3/modules/qemu/pages/qemu_vm_configuration_page.py, gns3/modules/qemu/qemu_vm.py, gns3/modules/qemu/ui/qemu_vm_configuration_page.ui, gns3/modules/qemu/ui/qemu_vm_configuration_page_ui.py, gns3/modules/virtualbox/pages/virtualbox_vm_configuration_page.py, gns3/modules/virtualbox/ui/virtualbox_vm_configuration_page.ui, gns3/modules/virtualbox/ui/virtualbox_vm_configuration_page_ui.py, gns3/modules/virtualbox/virtualbox_vm.py, gns3/modules/vmware/pages/vmware_vm_configuration_page.py, gns3/modules/vmware/ui/vmware_vm_configuration_page.ui, gns3/modules/vmware/ui/vmware_vm_configuration_page_ui.py, gns3/modules/vmware/vmware_vm.py
In addition to being a more "natural" naming scheme, some routers actually use that scheme for their default interface names (case in point: MikroTik RouterOS, which uses ether1, ether2, etc.).
This PR adds such a support for Qemu, VirtualBox and VMware, while also making sure that using EITHER one is allowed (and not just ```{0}```).
Largely for BC reasons, the numeric placeholders are still the same, but new named variables (```{port0}```, ```{port1}```, ```{segment0}```, ```{segment1}```) are added.
=> Port names with numbers starting from 1

gns3/dialogs/vm_with_images_wizard.py
In the case of ASA you need to select multiple image
on multiple screen. The problem is we refresh the list
of the VM on each step.
This patch refresh only the VM list when the widget is visible.
Fix #886
=> Fix select of image broken if you need to select multiple images

gns3/settings.py
In previous releases we got race conditions issues with
the OSX console due to the usage of Apple Script.
Problem. How to fix this situation for all users. Should
we reset terminal preferences for all OSX users coming from version
older than 1.4.1 ?
Fix #941
=> Fix only one console work for OSX

gns3/local_config.py, gns3/version.py
Following the issue #942
It's the easiest way to do it. But we can not interact
with the user at this step because the Qt is not yet started.
This mean during the upgrade the command is reset to the standard.
Even if some users could be disapointed it's positive for most user.
Because for most user the current settings is broke. And if someone
has change something he know how to configure it again (for example
switching to iTerm). If we don't do that I think the bug will remain
for years.
=> Reset the telnet command on Mac

gns3/graphics_view.py, gns3/serial_console.py, gns3/vnc_console.py
This PR rewrite the way multi link are created and avoid
to invert their directions.
Fix #954
=> Fix inversion of port label when loading a topology

gns3/servers.py, gns3/topology.py, tests/test_servers.py, tests/test_topology.py
When we load a topology we check if the server exist in our settings otherwise we ask the user to select a new server.
The user can refuse that and we will continue to create the server
from the topology. It's use the standard server list dialog to keep
code simple.
Fix #1144
=> If the server doesn't exists in settings we ask to replace it

gns3/schemas/topology.json, gns3/utils/import_project_worker.py
* Support import of GNS3Z on Linux https://github.com/GNS3/gns3-server/pull/481
* Warn if GN3VM is require Fix #1158
I removed in the schema the fact that host and port are mandatory for server because we don't use them for VM and local server.
=> Import improvements

gns3/main_window.py
I'm not sure at 100% but I think we need to
initialize the VM for all cases even we don't need the
autostart
Fix #1215
=> Always init the GNS3 VM

gns3/local_server.py, gns3/utils/http.py
Fix #1191
I added a Progress Dialog. This allow to use a Qt sleep for waiting the process instead of Python timeout. The issue with Python timeout is the HTTP query send to the server for asking it to shutdown will not close until Qt can read it this block the whole process.
=> Shutdown local server via controller

gns3/pages/general_preferences_page.py, gns3/ui/general_preferences_page.ui, gns3/ui/general_preferences_page_ui.py
This add in preferences a button to browse the configuration directory:
Fix #1321
=> A button to open the file browser with the configuration file location

gns3/items/link_item.py
This patch allow to remove any link even if node is already
running by stopping the node before. This solve the issue #1349
until we get a better support in 2.0.
Fix #1349
=> Stop node before hot unlink

gns3/qt/__init__.py, gns3/utils/progress_dialog.py
Always the same issue:
http://enki-editor.org/2014/08/23/Pyqt_mem_mgmt.html
I propose the creation of a qslot that we could use to decorate
all slot to protect them.
We can't wrap Signal or inherit from it :( So it's impossible to
do it for all slots without modifications everywhere.
Fix #1374
=> Protect one more method from deleted object

gns3/dialogs/export_debug_dialog.py, gns3/local_config.py, gns3/local_server.py, gns3/main.py, gns3/pages/general_preferences_page.py
This PR add a --profil command line arguments.
If set a new set of settings will be create in
~/GNS3/profiles/PROFILENAME
Otherwise it's use the default location.
This allow to test settings without losing original settings.
Also with the correct GUI this allow to switch from local server to a remote (home / office). For #1280
=> Support for profil settings

gns3/local_config.py
GNS3 patch level version are compatible (ex 1.5.3 and 1.5.2). But if you open settings from 1.6.1 with 1.5.1 you will have an error
The objective is to avoid corruption of the settings or project if your rollback to a previous version. I have seen weird issues when I rollback from 2.0 to 1.5.
Fix #1487
=> Display an error if settings come from a more recent version of GNS3

gns3/items/ethernet_link_item.py, gns3/items/serial_link_item.py, resources/icons/led_red.svg
Fix #1340 
This PR change the dot for the stop to a square in order to help colorblind people.
The square led icon is from the circle led same author:
https://openclipart.org/detail/30463/led-square-red
Result:
And for colorblind people:
=> Support for colorblind people

gns3/console_cmd.py, gns3/dialogs/notif_dialog.py, gns3/http_client.py, gns3/local_config.py, gns3/local_server.py, gns3/main_window.py, gns3/pages/general_preferences_page.py, gns3/settings.py, gns3/ui/general_preferences_page.ui, gns3/ui/general_preferences_page_ui.py
This PR add a new way (the target is to hide by default the console at bottom) to display the error, warning and info. They are in an overlay popup to make them more visual. 
* If you click on messages they are hidden. 
* Maximum 3 message is display on screen
* After a delay the messages are hidden (different by level)
* This a PR for GNS3 2.1
You can test the notif by typing in the console:
```
log info test
log warning test
log error test
```
It will probably need to be adjust, especially I think we will need to log less info messages.
Ref #1334
=> Display an overlay popup with log messages

gns3/main_window.py
This prevent opening a local .gns3 on a remote server.
Because this is not working you need to import the
project on the server using portable project.
Fix https://github.com/GNS3/gns3-server/issues/984
=> Disallow opening a .gns3 on a remote server

gns3/main_window.py
In all case when we close the main window we let the server
manage if he need to close or not the project.
Fix https://github.com/GNS3/gns3-server/issues/991
=> Fix project closing when we have multiple client connected

gns3/modules/dynamips/nodes/router.py, gns3/node.py
When you reopen a project you no longer have the
wic and slot, until you move the node and retrieve an
update. The settings is just lost in the GUI but is fine
on server.
Fix #2053
=> Fix lost slot and port in dynamips settings

gns3/topology.py, gns3/utils/export_project_worker.py, gns3/utils/import_project_worker.py, gns3/utils/progress_dialog.py
This trigger warning because you need to do the HTTP request
to the API from the main thread.
I also dropped some unused code in the import and export class.
Fix #2008
=> Do not run import / export of project in seperate thread

gns3/utils/file_copy_worker.py, tests/utils/test_file_copy_worker.py
This PR fixes problem when copying file with permissions. However, intentionally I don't give extra "x" flag (IOU needs this permission, but not other simulators). Let me know if make special case for IOU.
=> Preserve permissions while copying files. Fixes #2125.

gns3/graphics_view.py
Problem is because internal call when there is no elements to show. Idea is to disable/enable Node menu item. Waiting for nightly build for Windows to test, but should do the trick.
=> Toggle Node menu item (Fixes #2227)

gns3/qt/__init__.py
QXcbConnection log messages still pop up from time to time (even after 116cf5), filter them here as well.
=> Filter additional QXcbConnection log messages

gns3/settings.py
We have solution why uploads are slow on Windows, however after disabling debug mode makes that aiohttp screams:
`Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...\xc3\x8e\xa3'>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...\xc3\x8e\xa3'>)>
Traceback (most recent call last):
File "C:\Python36\lib\asyncio\events.py", line 127, in _run
self._callback(*self._args)
File "C:\Python36\lib\asyncio\proactor_events.py", line 188, in _loop_reading
self._closing)
AssertionError
b''`
Because of that, please don't merge it now.
=> Disable direct file upload on default

gns3/modules/docker/docker_vm.py, gns3/modules/docker/pages/docker_vm_configuration_page.py, gns3/modules/docker/pages/docker_vm_preferences_page.py, gns3/modules/docker/settings.py, gns3/modules/docker/ui/docker_vm_configuration_page.ui, gns3/modules/docker/ui/docker_vm_configuration_page_ui.py, gns3/schemas/appliance.json
Corresponds to pull request in gns3-server: https://github.com/GNS3/gns3-server/pull/1584
Provides the UI changes to configure the persistent volumes. There is also an additional patch to style the extra_hosts text edit in the same way as the extra_volumes one.
=> Custom persistent docker volumes

gns3/graphics_view.py, gns3/modules/qemu/qemu_vm.py, gns3/node.py
Implements idea from https://github.com/GNS3/gns3-server/pull/1801:
> * show the import/export/edit config option only, when the config option is selected for that VM
>   That is tricky as currently `hasattr(instance, "exportConfigs")` is used to test if a config is available. My idea is to always have the exportConfigs method, but test if it returns an non-empty list. But as this is used in a lot of places this will be a large change.
This PR creates a dummy exportConfigs method in the node class, so `hasattr(instance, "exportConfigs")` is always true for node items and doesn't need to be checked. The check, if a config file is available, is now done by testing if exportConfigs() returns a non-empty list of files. A boolean False value (False / None / empty list) means, that no config …
=> Hide config import/export when configFiles attribute is empty

gns3/graphics_view.py, gns3/modules/qemu/qemu_vm.py, gns3/node.py
Implements idea from GNS3/gns3-server#1801:
>  * the edit config makes no sense for binary config data like the zip file. But I have no good idea how to limit the edit function to text configurations.
Added the method `configTextFiles`, which returns only config files, that are pure text files. By default, that method returns the list of config files. But this method can be overridden to return only a subset of config files. In case of QEMU VMs, it resturns no fiiles.
=> Edit only text mode config files

gns3/dialogs/setup_wizard.py
Replaced old dead VMWare link with current 1.17 version link.
It should be noted that this link is for 64-bit Linux and Windows only.  Mac users need to find another way.
=> Fixed dead VIX API link

gns3/graphics_view.py
Fixed a rare case (that happened to me) where drawLine was called with float arguments (rect.top(), rect.bottom(), rect.left(), rect.right()) preventing from drawing the background grid
=> Fixed drawLine called with float arguments

tests/test_link.py
The create_link test is failing with the following error.  This started after this change: https://github.com/GNS3/gns3-gui/commit/545a9f53#diff-c82fb679ee95de7e79fd605f3c46960711ca921079b55a6f665869a3b19d2aafL94-L95
I think the change in this PR will resolve the issue.  I believe the lines in the test were missed when creating the above change.
```
_______________________________ test_create_link _______________________________
devices = (<gns3.modules.vpcs.vpcs_node.VPCSNode object at 0x7f376d193d00>, <gns3.modules.vpcs.vpcs_node.VPCSNode object at 0x7f376d193eb0>)
project = <gns3.project.Project object at 0x7f376d192e60>
controller = <MagicMock id='139876008795088'>
def test_create_link(devices, project, controller):
link = Link(devices[0], devices[0].ports()[0], devices[1], …
```
=> Fix create_link test

gns3/graphics_view.py
While shift+dropping devices, QPoint would be called with floats, preventing the insertion of devices.
This is a simple fix like https://github.com/GNS3/gns3-gui/pull/3272
Because these issues have been occurring since python3.10, would it be preferable to look for the root issue?
=> Fixed QPoint called with floats

gns3/update_manager.py
Hello the GNS3 team! I'm the developer of Kaisen Linux, a distribution for network and system administrators.
By default, the gns3-gui software is included. The company Trellix has contributed to my Debian package gns3-gui to add a patch on the CVE-2007-4559. The details here of their contribution: https://github.com/kaisenlinux/gns3-gui/pull/1
I'm transferring their patch to you via this PR so you can integrate it upstream.
=> CVE-2007-4559 patch

gns3/utils/sudo.py
The sys module is missing into the gns3/utils/sudo.py file. Capabilities required for ubridge cannot be set without this module.
Reported from Kaisen Linux (based on Debian trixie (testing)) with Python 3.11.4. GNS3 server, ubridge and dynamips also installed on my computer.
=> Add import sys in sudo.py

gns3/ui/main_window.ui, gns3/ui/main_window_ui.py
This PR introduces a new keyboard shortcut, **Ctrl+L**, for the "Add Link" tool in the GNS3 GUI. The shortcut provides faster access to the link creation functionality, improving workflow efficiency for users frequently adding links between devices.
- Added **Ctrl+L** as a keyboard shortcut to activate the "Add Link" tool
- Verified the shortcut works as expected on NixOS 24.05
This small enhancement aims to streamline the process of linking devices in GNS3 by providing a direct, convenient shortcut
=> Add Keyboard Shortcut (Ctrl+L) for Add Link Tool

gns3/graphics_view.py, gns3/style.py
Adds ability to customize grid colors through CSS by exposing grid colors as Qt properties. Grid colors can now be styled via theme CSS files using:
``` css
QGraphicsView {
qproperty-drawingGridColor: #someColor;  /* Controls finer grid lines */
qproperty-nodeGridColor: #someColor;     /* Controls major grid lines */
}
```
If these properties are not defined in a theme's CSS, the grid colors fall back to their original default values. Grid colors are automatically reset when switching themes to ensure proper fallback behavior.
- Added Qt property getters/setters for grid colors in GraphicsView
- Added resetGridColors() method to handle theme changes  
- Modified Style class to reset grid colors when switching themes
- No changes to default behavior when CSS properties aren't specified
- …
=> Add CSS Grid Color Customization Support
