GNS3/gns3-gui

- gns3/servers.py
> Fix crash is no remote servers is available

- gns3/project.py
Perhaps this can fix #208. But I'm not sure if it's a good solution.
> Default project name

- gns3/modules/dynamips/nodes/etherswitch_router.py
> Fix crash in etherswitch router

- gns3/pycutext.py
I think this will improve debugging.
> Display print( in std console and Qt Console

- gns3/nodes_view.py
It's the most common issue on the support forum.
> Display an error and link to the documentation if no router available

- gns3/graphics_view.py
See
https://community.gns3.com/ideas/1680
> Double click on node to configure

- gns3/modules/qemu/dialogs/qemu_vm_wizard.py
> Add support for IOS-XRv under qemu wizard.

- gns3/graphics_view.py
Corresponding idea:
https://community.gns3.com/ideas/1426
> If you doubleclick on a label we open the change hostname dialog

- gns3/topology.py
- gns3/topology_check.py
- gns3/utils/get_resource.py
- requirements.txt
- resources/topology_schema.json
- setup.py
- tests/schemas/dynamips_ios.gns3
- tests/schemas/dynamips_standard_devices.gns3
- tests/schemas/empty.gns3
- tests/schemas/geometry.gns3
- tests/schemas/iou.gns3
- tests/schemas/note.gns3
- tests/schemas/qemu.gns3
- tests/schemas/twovpcs.gns3
- tests/schemas/virtualbox.gns3
- tests/test_topology.py
- tests/test_topology_check.py
Support:
* IOU
* Dynamips
* VPCS
* VirtualBox
* Qemu
VMWare is not supported
Tests schema are available in:
tests/schemas
And the test suite is auto generated from this directory you
can take a look to test_topology_check
Fix #342,#392,#384
> JSON schema for checking topologies

- gns3/dialogs/node_properties_dialog.py
- gns3/dialogs/preferences_dialog.py
- gns3/graphics_view.py
- gns3/http_client.py
- gns3/main_window.py
- gns3/progress.py
- gns3/qt.py
- gns3/servers.py
- tests/test_progress.py
setWindowModality(Qt.Qt.ApplicationModal) allow to have the progress
dialog modal for the app
Creation of a context block where you can temporary change the
behavior of the progress dialog.
Fix #359
> Refactor of the progress dialog

- gns3/dialogs/preferences_dialog.py
This Gray out the apply button by default. If something change
the button apply is enabled.
If you try to exit the windows without saving you got a warning.
The change detection is made by binding to various signal of the
preferences dialog childrens.
This work also when coming from the setup wizard.
Fix #515
> Inform user before exiting preferences dialog with changes

- gns3/graphics_view.py
- gns3/http_client.py
- gns3/modules/qemu/pages/qemu_vm_configuration_page.py
- gns3/project.py
- gns3/qt.py
- gns3/topology.py
- tests/test_http_client.py
This function detect is the QObject is deleted and
doesn't call the callback.
Fix #596, #735
> Add a Qt compatible version of partial

- gns3/http_client.py
- gns3/network_client.py
- gns3/project.py
- gns3/server_summary_view.py
- gns3/servers.py
- gns3/ui/main_window.ui
- gns3/ui/main_window_ui.py
- tests/test_servers.py
Fix #963
Not sure if we should merge it today
> Show a summary with server usages

- gns3/console_view.py
- gns3/dialogs/doctor_dialog.py
- gns3/main_window.py
- gns3/modules/vmware/__init__.py
- gns3/ui/doctor_dialog.ui
- gns3/ui/doctor_dialog_ui.py
- gns3/ui/main_window.ui
- gns3/ui/main_window_ui.py
Warn user about issues with AVG
Fix #928, #744
> Show a dialog for checking some common issues

- gns3/graphics_view.py
- gns3/vm.py
- tests/modules/qemu/test_qemu_vm.py
> Allow to show the command line used to start a VM

- gns3/modules/qemu/__init__.py
- gns3/modules/qemu/pages/qemu_vm_preferences_page.py
- gns3/nodes_view.py
At this time only Qemu is done
If the change are OK I can patch VMware, VirtualBox, Dynamips and IOU.
Fix #670
> Allow to edit a node via a right click in the node

- gns3/dialogs/setup_wizard.py
- gns3/ui/setup_wizard.ui
- gns3/ui/setup_wizard_ui.py
It's smart the link change with the version and emulator
Fix #978
> Put a link for the GNS3 VM in the setup wizard

- gns3/dialogs/doctor_dialog.py
> Check if GNS3 is not installed twice in doctor

- gns3/vm.py
Detect and fix duplicate port name in topology
Seem to fix #992.
> Detect corrupt port name

- gns3/graphics_view.py
- gns3/vm.py
- tests/test_vm.py
Without saving the console anywhere
Fix #675
> Allow to open a custom console on any node

- gns3/gns3_vm.py
- gns3/utils/wait_for_vm_worker.py
> Allow to cancel the start of the GNS3 VM

- gns3/dialogs/setup_wizard.py
- gns3/main_window.py
- gns3/pages/server_preferences_page.py
- gns3/utils/progress_dialog.py
This is the final countdown!
https://www.youtube.com/watch?v=oZxnbBWtGR4
Fix #912
> Countdown before starting the GNS3 VM

- gns3/utils/wait_for_vm_worker.py
Instead of upgrading from the GUI my proposal is to improve the error message.
Fix #1053
> Ask user to upgrade via the VM menu

- gns3/main_window.py
- tests/test_servers.py
> At startup display a warning if another GUI is already running

- gns3/main_window.py
- gns3/progress.py
- tests/test_progress.py
> Remove bad smell from progress dialog and handle ESC key

- gns3/http_client.py
> Add a timeout when you are not able to join the remote server

- gns3/ui/new_project_dialog.ui
- gns3/ui/new_project_dialog_ui.py
> If you hit enter in the new project dialog it's work

- gns3/progress.py
- gns3/utils/__init__.py
> Display upload size during progress

- gns3/progress.py
> This should avoid blinking dialog. And display better progress

- gns3/main_window.py
> Block save and snapshot when a device is running

- gns3/dialogs/snapshots_dialog.py
> Sort snapshots by date

- gns3/topology_summary_view.py
> Double click on an element in topology summary center the view on it

- gns3/main_window.py
https://github.com/GNS3/gns3-server/issues/590
> Disallow export of project with a cloud

- gns3-gui.appdata.xml
- gns3-gui.desktop
Please find this PR which adds AppData and Desktop files for Gnome software support (Cross distro app store-like)
> Add AppData and Desktop files for Gnome software support and such

- gns3/modules/vmware/ui/vmware_vm_wizard.ui
- gns3/modules/vmware/ui/vmware_vm_wizard_ui.py
Proposal for fixing #1420 
* Add the mention of supported products
* Make clear that remote server is a GNS3 server
> Make more clear that VMware VM are not ESXi

- gns3/base_node.py
- gns3/graphics_view.py
- gns3/modules/builtin/__init__.py
- gns3/modules/builtin/nat.py
- gns3/modules/builtin/settings.py
- gns3/node.py
> A nat node

- gns3/main_window.py
This PR propose to allow GNS3 to open only file with a known extension
Fix #1490
> Dissallow unknown extensions

- gns3/graphics_view.py
It's like other messages display during 2 seconds.
Fix #1263
> Display zoom percentage when changing scale.

- gns3/local_config.py
- gns3/modules/qemu/ui/qemu_vm_configuration_page.ui
- gns3/modules/qemu/ui/qemu_vm_configuration_page_ui.py
- gns3/registry/appliance.py
- tests/registry/test_appliance.py
- tests/test_local_config.py
See https://github.com/GNS3/gns3-server/pull/895 for server part
> Allow up to 275 adapters for qemu

- gns3/main_window.py
- gns3/status_bar.py
- gns3/ui/main_window.ui
- gns3/ui/main_window_ui.py
- resources/icons/warning.svg
- resources/resources.qrc
You can test it by typing in the console:
log error test
log warning test
Click on the count hide / show the console and reset the counters.
Also now status bar is a dedicated class we can easyly extend it.
Ref #1864
> Display a count of errors at the bottom of the screen

- gns3/application.py
- gns3/local_config.py
- gns3/main.py
- gns3/pages/general_preferences_page.py
- gns3/settings.py
- gns3/ui/general_preferences_page.ui
- gns3/ui/general_preferences_page_ui.py
> Disable HDPI by default on Linux and allow to configure it

- gns3/local_server.py
It's the best solution I found. Streaming in real time
the log will require to start an aditionnal thread
Fix #1880
> Monitor and display local server stderr

- gns3/dialogs/doctor_dialog.py
- gns3/local_server.py
> Catch missing function listxattr on some linux host

- gns3/main.py
> Drop support for Qt before 5.5 (ubuntu trusty)

- Dockerfile
- gns3/controller.py
- gns3/http_client.py
- gns3/main.py
- gns3/project.py
- gns3/qt/__init__.py
- tests/test_http_client.py
> Use websocket for notifications

- gns3/main_window.py
- tests/test_main_window.py
Do you have a better idea to handle this case?
> Fixes #2137

- gns3/dialogs/filter_dialog.py
- gns3/items/ethernet_link_item.py
- gns3/items/link_item.py
- gns3/items/serial_link_item.py
- gns3/link.py
- gns3/pages/server_preferences_page.py
- gns3/topology_summary_view.py
- gns3/ui/filter_dialog.ui
- gns3/ui/filter_dialog_ui.py
- resources/icons/filter-capture.svg
- resources/icons/filter-reset.svg
- resources/icons/filter.svg
- resources/resources.qrc
- tests/test_link.py
Ref #765
Will require some improvement like an icon. But should work.
> Filter packet interface

- gns3/dialogs/filter_dialog.py
- gns3/items/link_item.py
- gns3/topology_summary_view.py
- gns3/ui/filter_dialog.ui
- gns3/ui/filter_dialog_ui.py
> BPF filter support

- gns3/packet_capture.py
> Fix Wireshark is restarted when updating packet filters

- gns3/items/ethernet_link_item.py
- gns3/items/link_item.py
- gns3/items/serial_link_item.py
- gns3/link.py
- gns3/node.py
- gns3/topology_summary_view.py
Fix https://github.com/GNS3/gns3-gui/issues/1295
> Suspend link

- gns3/qt/__init__.py
- gns3/topology.py
We dynamically change to the best available network when the network is lost.
Fix #2104
> Fix issues when Wifi is turned off

- gns3/http_client.py
- gns3/local_server.py
- gns3/main_window.py
- gns3/utils/http.py
> Try to fix segfault at exit

- gns3/dialogs/project_dialog.py
- gns3/graphics_view.py
- gns3/node.py
- gns3/project.py
> Allow to duplicate a node

- gns3/local_server.py
Ref https://twitter.com/andreppires/status/889594139800719360
> Make sure ubridge path is not a directory

- gns3/nodes_view.py
> Fixes exception when right click on Dynamips router in the device dock

- gns3/modules/builtin/ui/cloud_configuration_page.ui
- gns3/modules/builtin/ui/cloud_configuration_page_ui.py
- resources/icons/dialog-warning.svg
- resources/resources.qrc
This is test if on Windows Qt will find this icon as fallback, otherwise we will just use provided icon.
> dialog-warning.svg fallback for themed icon (Ref. #2245)

- gns3/dialogs/snapshots_dialog.py
- gns3/http_client.py
- gns3/utils/create_snapshot_worker.py
- gns3/utils/progress_dialog.py
It does cancel query however we're blocked by MD5 not async calculation.
> Snapshoting project without timeout but with Cancel button. Ref. #2314

- gns3/ui/setup_wizard.ui
- gns3/ui/setup_wizard_ui.py
> Fix a minor typo in the setup wizard

- gns3/ui/edit_project_dialog.ui
- gns3/ui/general_preferences_page.ui
- gns3/ui/gns3_vm_preferences_page.ui
- gns3/ui/packet_capture_preferences_page.ui
- gns3/ui/preferences_dialog.ui
- gns3/ui/project_dialog.ui
'Fixed' tab order in edit project and preferences dialogs so they follow the layout
> Tab Order in Preferences and Project Dialog

- gns3/modules/qemu/pages/qemu_vm_configuration_page.py
- gns3/schemas/appliance.json
See https://github.com/GNS3/gns3-server/pull/1714
> GUI changes to support recent versions of Qemu

- gns3/modules/qemu/pages/qemu_vm_configuration_page.py
- gns3/modules/qemu/qemu_vm.py
- gns3/modules/qemu/settings.py
- gns3/modules/qemu/ui/qemu_vm_configuration_page.ui
- gns3/modules/qemu/ui/qemu_vm_configuration_page_ui.py
This would fix this issue: https://github.com/GNS3/gns3-server/issues/1767
> Support to activate/deactive network connection state replication in Qemu

- gns3/main_window.py
These buttons have can be dangerous (looking at you stop/reload). Prompt user to see if they really want to do this and didn't just hit that by accident.
> Add yes/no prompts to gui for global project level buttons start/stop/reload/suspend to prevent bad day.

- gns3/graphics_view.py
- gns3/modules/docker/docker_vm.py
- gns3/modules/dynamips/nodes/router.py
- gns3/modules/dynamips/pages/ios_router_configuration_page.py
- gns3/modules/iou/iou_device.py
- gns3/modules/iou/pages/iou_device_configuration_page.py
- gns3/modules/qemu/qemu_vm.py
- gns3/node.py
The checks are done on the server now
> Remove valid hostname checks for Dynamips, IOU, Qemu and Docker nodes

- gns3/settings.py
[#3193 ](url) related commit added the profile, but added it to OS X platform not Windows.
- Remove OS X profile
- Add to Windows profile
> Changed Windows Terminal telnet console profile from OS X to Windows ref: #3193

- gns3/settings.py
Add KDE KRDC to the list of pre-configured VNC viewers
> Add KRDC to pre-configured VNC console commands
